name: "Build Package"
env:
  DOCKER_COMPOSE_VERSION: 1.23.0

on:
    pull_request:
        branches:
          - master
          - release-*
          - new*
        #types: [closed]
    push:
        tags:
          - v*
jobs:
  BUILD_PACKAGE:
    #if: github.event.pull_request.merged == true
    env:
        BUILD_PACKAGE: true
    runs-on:
            #- self-hosted
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.7
        id: go
      - uses: actions/checkout@v2
        with:
          path: src/github.com/danfengliu/harbor_test
      - name: Build Package
        run: |
          cd src/github.com/danfengliu/harbor_test
          env
          df -h
          echo "================"
          echo ${{ secrets.MY_H }}
          echo "================"
          echo $HARBOR_SIGN_KEY
          echo -en "${{ secrets.HARBOR_SIGN_KEY }}" |  gpg --import
